# Generated by Django 6.0 on 2025-12-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tovar/gallery')),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.tovar')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
